--------------------------------------------------------------------------------
-- Plugin Config
--------------------------------------------------------------------------------
require('plugins.whichkey')
require('plugins.devicons')
require('plugins.lualine')
-- require('plugins.shade')
-- require('plugins.neoscroll')
require('plugins.gitsigns')
require('plugins.nvim-tree')
require('plugins.sandwich')
require('plugins.autopairs')
require('plugins.comment')
require('plugins.hop')
-- require('plugins.lightspeed')
require('plugins.quickscope')
require('plugins.treesitter')
require('plugins.telescope')
-- require('plugins.lsp-coq')
require('plugins.lsp-cmp')
